---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "svanalyzer_svbenchmark"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::svanalyzer=0.35"
